Budget bee v1.0
iamsjunaid/budget-bee pull request #1
Opened 2023-09-20 10:45 UTC by iamsjunaid

2023-09-21 16:25 UTC, KDlamini requested changes
### Hi @iamsjunaid  🙋‍♀️,  

Great work so far! 💯 
You have done a great job creating a working Budget app using Rails 7. 🎊 🥳 
There are some issues that you still need to work on to improve your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞

✔️  Professional pull request title and description
✔️  Well-documented and profesional README
✔️  There's user authentication, register and log in so that the data is private to them
✔️  Model validations are present
✔️  Controllers, Migrations, Views, and Routes are set up correctly

## Video Presentation

✖️ Please add a link to a public video, your video is currently private

## Required Changes ♻️

**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-21 16:25 UTC, KDlamini commented on README.md
> +
🚀  Great job on deploying the project on render successfully 💯 

Although I have highlighted the live demo link, this review is for the `presentation video` link you provided on the pull request description.

- The Youtube link for the presentation video is private. Kindly make sure that you make the video public or unlisted so that it accessable to other users.

![image](https://github.com/iamsjunaid/budget-bee/assets/38088818/b1be8f17-603f-4802-b1c4-b7c4d6ee31f1)

2023-09-21 16:25 UTC, KDlamini commented on README.md
> +
[OPTIONAL] To improve your README, I think it would be best if you included links to the authors profile and the Behance website so that users are able to check Gregoire's work. Thanks to you users will now be aware of his other designs.

For example:
I would like to give credit to  [Gregoire Vella on Behance](https://www.behance.net/gregoirevella) the [author of the original design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), for the inspirational source of this project as required by the [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/).

2023-09-21 16:25 UTC, KDlamini commented on app/views/devise/registrations/new.html.erb
> +    <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
Great job with the user authentication pages 👏🏾 

Kindly try to match the Behance design as closely as possible. In this milestone you are required to follow the exact design from [the design guideline](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=). This means that the layout composition of the registration page should look exactly like this:

![image](https://github.com/yodit93/budget-app/assets/38088818/6b7bcddb-1d8d-4352-8ed8-48d73371b6be)

This means that:

- There should be a  navbar with the background color `#3778c2`.  There should be a back arrow that navigates back to the splash screen, a "REGISTER" heading, and a "next" button on the right that serves as the "sign up" button.
- The "Full name", "Email", and "password fields should have a top and bottom border but no right and left borders, and the border color is `#F4F4F4`.
- There should be no labels for the input fileds but placeholder text with a light gray color in each input filed.


Your registration page:

![image](https://github.com/iamsjunaid/budget-bee/assets/38088818/42e005d6-0dd5-4109-9ee6-2c84ee9cd5ca)

2023-09-21 16:25 UTC, KDlamini commented on app/views/devise/sessions/new.html.erb
> +      <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "invisible" %>
The same thing applies to the login page. Kindly refer to the [Behance website](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=) for reference.

Kindly fix the navbar, input fields height, text colors, and layout as it is on the design. 

- The `log in` button should be on the top left side of the navbar.
- The `Signup` button should be removed.
- The `Forgot your password?` text should be centered and gray in color.
- The height/padding of the  input fields should be slightly increased.


The layout composition of the login page should look exactly like this:

![image](https://github.com/yodit93/budget-app/assets/38088818/10ba3596-d411-4bcc-9662-0d29cf4c4576)

Your login page:

![image](https://github.com/iamsjunaid/budget-bee/assets/38088818/4bdb1b4c-e5e5-4789-a4c1-023c9a7ad806)

2023-09-21 16:25 UTC, KDlamini commented on app/views/categories/index.html.erb
> +    <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
Kindly try to match the button with the Behance design.

- It would be best to add a white border around the button text
- There button text should also be white and uppercase

![image](https://github.com/iamsjunaid/budget-bee/assets/38088818/fb1db4e8-be04-44a1-8004-bed833ff2a42)

Your button:
![image](https://github.com/iamsjunaid/budget-bee/assets/38088818/0cb61943-bc19-4d72-adfb-115adbbc36c2)

The same thing applies to your add transaction button:

![image](https://github.com/iamsjunaid/budget-bee/assets/38088818/7f456369-baa7-4692-90cb-544fafb79e2a)

- Kindly make sure that transactions button fills 100% of the mobile view width.

2023-09-21 16:25 UTC, KDlamini commented on app/views/categories/new.html.erb
> +    <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
Kindly fix the layout of the `new category` form page, and `transactions` page.

#### New category form

- The input fields and button are  perfectly visible. Kindly make sure that the content is perfectly aligned on the page.

![image](https://github.com/iamsjunaid/budget-bee/assets/38088818/fce0c502-3b4e-438e-8c80-27b4bc0b261e)

#### Transaction page

- At the top of the page the total amount for the category should be tubular similar to the category card with the category name on the left and price on the right.
- Kindly make sure that the transactions tab fills 100% of the mobile view width with the transaction name on the left and price on the right. This card must also be tabular.

You should have something similar to this, although in this case you do not have to match 100% of the design:

![image](https://github.com/iamsjunaid/budget-bee/assets/38088818/4c0b218a-6b78-4872-8c82-372869cc4aaf)

Your transaction page:

![image](https://github.com/iamsjunaid/budget-bee/assets/38088818/0719dc83-475a-4069-b742-ce885d759128)

2023-09-21 16:25 UTC, KDlamini commented on app/views/purchases/new.html.erb
> +    <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link' %></li>
#### New transaction form

As per project requirements, there should be a `mandatory` drop down button that have a list of all created categories to choose from. The transaction that is saved should be for the category that is picked on the drop down list of available categories.

![image](https://github.com/iamsjunaid/budget-bee/assets/38088818/e134fce9-fc52-4c98-b267-20eb748c4f38)

![image](https://github.com/iamsjunaid/budget-bee/assets/38088818/528d71fb-ce4a-4f69-ad32-2e69a06fafa5)

2023-09-21 16:25 UTC, KDlamini commented on spec/features/category_index_spec.rb
🚀  Fantastic job adding sufficient and passing unit and integration specs!!! 👏🏾 💯 

![image](https://github.com/iamsjunaid/budget-bee/assets/38088818/85f30d25-efd7-4003-ade7-742cdce297fd)

2023-09-22 10:54 UTC, iamsjunaid commented
Hi @KDlamini,  I have made all the requested changes. I have updated the privacy of the video so it is now available to all.

2023-09-22 13:20 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @iamsjunaid 

Great work on making the changes requested by a previous reviewer 👏! I really appreciate the effort you put in!  **_However, there are few this that still need to be fixed. But you are almost there!_** 💪 🏁

![so close](https://media.tenor.com/3sCHnD_x2RIAAAAC/almost-there.gif)


## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ Good job with the design
- ✅ Descriptive PR and README file
- ✅ Correct Linters

## Required Changes 🛑

- [ ] Great video demonstration of the project. However, please make sure that video should be maximum of 5 minutes in length as per [this requirement](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=It%20is%20a%20video%20with%20a%20maximum%20length%20of%205%20minutes)

_Please check the comments under the review._

## Optional suggestions ❕

_Please check the comments under the review._


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-22 13:20 UTC, KanzaTahreem commented on app/assets/stylesheets/application.css
> +}
- [ ] Amazing job so far, just a little bit of effort is needed here 🙌 As the previous reviewer suggested [here](https://github.com/iamsjunaid/budget-bee/pull/1#:~:text=be%20white%20and-,uppercase,-Your%20button%3A), kindly make sure that the button text is in `uppercase`
- [ ] I noticed that a border for the button is present. Since this was not asked by the reviewer and is not present in the design guidelines, therefore please rectify this. _Kindly note that this comment is not about removing the border around the button text_
- [ ] You have done a great job by adding border around the button text, however it is not according to the given design. I noticed that there's a little more space on the left and right side of the button than needed. Kindly have a look at the following comparison and try to match the button with the Behance design as mentioned by the previous reviewer [here](https://github.com/iamsjunaid/budget-bee/pull/1#:~:text=Kindly%20try%20to%20match%20the%20button%20with%20the%20Behance%20design.). 

Given design | Current design
---| ---|
![image](https://github.com/iamsjunaid/budget-bee/assets/106119105/d3d9ed9c-0bec-4372-9524-c50b7a537bf4) | ![image](https://github.com/iamsjunaid/budget-bee/assets/106119105/f37adfc8-684e-4844-bc5c-52f07527b417)


**_The same also applies to the transaction/purchase button_**

2023-09-22 13:20 UTC, KanzaTahreem commented on app/views/purchases/new.html.erb
> +  <div class="mb-4">
- [ ] As the previous reviewer [mentioned here](https://github.com/iamsjunaid/budget-bee/pull/1#:~:text=the%20transaction%20name%20on%20the%20left%20and%20price%20on%20the%20right.), kindly make sure that the transaction name is on the left and price is on the right side of the transaction/purchase card
- [ ] Well done for adding a dropdown for selecting a category of the purchase.  As the previous reviewer mentioned, please make sure that the transaction that is saved should be for the category that is picked on the drop down list of available categories. Right now, even though after selecting a different category from the dropdown, the transaction/purchase is not adding to that category. Kindly have a look at the video below for better clarity  💡


https://github.com/iamsjunaid/budget-bee/assets/106119105/bc184007-6b99-4744-910b-903c392fe77c

2023-09-22 13:20 UTC, KanzaTahreem commented on app/views/devise/sessions/new.html.erb
> +<%= form_for(resource, as: resource_name, url: session_path(resource_name), html: { class: 'mt-10 flex flex-col' }) do |f| %>
- [ ] Great effort with the login page 👏👏 But, as the previous reviewer [mentioned here](https://github.com/iamsjunaid/budget-bee/pull/1#:~:text=Kindly%20fix%20the%20navbar), kindly fix the navbar according to the given design guidelines. For that I think it would be better to add some padding to it following the given design guidelines. Also, I noticed that some padding was also present in the last review. Since the previous reviewer didn't asked to remove it, therefore please rectify this
- [ ] Also, please make sure to implement the following as previous reviewer requested 👇
  - _The log in button should be on the top left side of the navbar as [highlighted here](https://github.com/iamsjunaid/budget-bee/pull/1#:~:text=The%20log%20in%20button%20should%20be%20on%20the%20top%20left%20side%20of%20the%20navbar.)_
  - _The Forgot your password? text should be centered and gray in color as [highlighted here](https://github.com/iamsjunaid/budget-bee/pull/1#:~:text=The%20Forgot%20your%20password%3F%20text%20should%20be%20centered%20and%20gray%20in%20color.)_


Given design | Current design 
---| ---|
![image](https://github.com/iamsjunaid/budget-bee/assets/106119105/066589b0-baeb-411c-b8ce-aa075f1f5b1d) | ![image](https://github.com/iamsjunaid/budget-bee/assets/106119105/fe502ae6-68c6-407f-8867-5673de41c52a)

2023-09-22 13:20 UTC, KanzaTahreem commented on app/views/devise/registrations/new.html.erb
> +<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { class: 'mt-10 flex flex-col' }) do |f| %>
- [ ] Amazing effort from your side and well done with the navbar💪please make sure that we have a "next" button on the right side of the navbar that serves as the "sign up" button as suggested by the reviewer [here](https://github.com/iamsjunaid/budget-bee/pull/1#:~:text=There%20should%20be%20a%20navbar%20with%20the%20background%20color%20%233778c2.%20There%20should%20be%20a%20back%20arrow%20that%20navigates%20back%20to%20the%20splash%20screen%2C%20a%20%22REGISTER%22%20heading%2C%20and%20a%20%22next%22%20button%20on%20the%20right%20that%20serves%20as%20the%20%22sign%20up%22%20button.)


Given design | Current design 
---| ---|
![image](https://github.com/iamsjunaid/budget-bee/assets/106119105/fbb8b6e9-2a0c-4aba-b3d7-eb1017a7e439) | ![image](https://github.com/iamsjunaid/budget-bee/assets/106119105/27d599c6-a460-434d-8b3f-88d4e74af625)

2023-09-22 13:20 UTC, KanzaTahreem commented on app/views/splash/index.html.erb
- [OPTIONAL] I think it would be better to style the splash screen according to the design guidelines we have. What do you think about this? ✨⛏

2023-09-22 17:38 UTC, t-yanick approved these changes
# STATUS: MILESTONE APPROVED :1st_place_medal: 

Hi @iamsjunaid , 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark: Requested changes implemented 👍 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-23 04:11 UTC, merged